### ISSUE TITLE
Add a tool for removing html character entities from geojson

### ISSUE THREAD

**Issue by JesseCrocker** [trailbehind/TilingTools#1]
Convert entities to actual characters. Only needs to process properties, not geometries.

**Comment by jczaplew** [comment]
Can I assume the GeoJSON will be line-delimited?

**Comment by JesseCrocker** [comment]
I guess so, it looks like gdal always outputs line delimited

**Comment by jczaplew** [comment]
Many, but not all, tools do. For a first pass I'll assume line delimination because it allows us to read the file line-by-line, preventing memory issues with large files.
